name: 'Linux Http Action'
description: 'Github Action for Linux Http Client'
inputs:
  issuer:  # id of input
    description: 'Jwt Issuer'
    required: true
  secret:
    description: 'Jwt Secret'
    required: true
  url:
    description: 'Linux Http server url'
    required: true
  cmd:
    description: 'Linux Command'
    required: true
  input:
    description: 'Input'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    JWT_ISSUER: ${{ inputs.issuer }}
    JWT_SECRET: ${{ inputs.secret }}
    JWT_URL: ${{ inputs.url }}
    LH_CMD: ${{ inputs.cmd }}
    LH_INPUT: ${{ inputs.input }}
